name: prod-build

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    env:
      ACTIONS_BUILD_COMMAND: npm run build
      ACTIONS_BUILD_DIST: dist
      ACTIONS_LOCK_FILE: package-lock.json

      NEXT_PUBLIC_SITE_ORIGIN: "https://board.fnobi.com"
      NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyChgUANl0kHf8sZpfIlUbAeeHiDKKeIVUQ"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "fnobi-kakikaki.firebaseapp.com"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: "fnobi-kakikaki"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "fnobi-kakikaki.firebasestorage.app"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "211652633359"
      NEXT_PUBLIC_FIREBASE_APP_ID: "1:211652633359:web:255108644ffc13a51c147a"

      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('**/{0}',env.ACTIONS_LOCK_FILE)) }}
          restore-keys: ${{ runner.os }}-node-

      - name: install dependencies
        run: npm ci

      - name: build
        run: ${{ env.ACTIONS_BUILD_COMMAND }}

      - name: setup credential
        run: echo ${{ secrets.SERVICE_ACCOUNT_KEY }} | base64 --decode > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: install firebase tools
        run: npm -g install firebase-tools

      - name: deploy
        run: firebase deploy --project ${{ env.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} --only hosting,firestore
