name: prod-build

on:
  push:
    branches:
      - develop

env:
  ACTIONS_BUILD_COMMAND: pnpm run build
  ACTIONS_BUILD_DIST: dist
  ACTIONS_LOCK_FILE: pnpm-lock.yaml

  NEXT_PUBLIC_SITE_ORIGIN: "https://m-visioning.web.app"
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyDcXGainNXgKNCFztf9lDf-Ga8HtU7TtM4"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "m-visioning.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "m-visioning"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "m-visioning.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "964843675967"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:964843675967:web:929f1ff4a79631aa68f38a"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('**/{0}',env.ACTIONS_LOCK_FILE)) }}
          restore-keys: ${{ runner.os }}-node-

      - name: install dependencies
        run: pnpm install

      - name: build
        run: ${{ env.ACTIONS_BUILD_COMMAND }}

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: deploy
        env:
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: pnpm exec firebase deploy --project ${{ env.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} --only hosting,firestore
